#!/usr/bin/env bash
# Installs, configures, and starts the load balancer
# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install haproxy -y

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 223186-web-01 52.90.15.100:80 check
    server 223186-web-02 54.89.59.115:80 check
EOT

# Test HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Start HAProxy
sudo systemctl start haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy
